#!/bin/sh
sudo yum install  epel-release -y
curl -sSLO https://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
sudo rpm -Uvh mysql80-community-release-el7-5.noarch.rpm
rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
sudo yum install mysql-server -y
sudo systemctl start mysqld
sudo systemctl status mysqld
